name: github pages

on:
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: "16.x"

      - run: npm ci
      - run: npm run predeploy
      - run: npm run deploy
